### ISSUE TITLE
Fails if display environment variable is not set

### ISSUE THREAD

**Issue by dylanfprice** [alzadude/ansible-firefox-addon#1]
On my machine, $display is empty (instead it is $DISPLAY) which causes [ensure_profile](https://github.com/alzadude/ansible-firefox-addon/blob/master/library/firefox_addon#L18) to interpret "addon_profile" as the display arg, leading to this error message:

```
{ "failed": true, "msg": "couldn't determine profile path", "stdout": "Error: cannot open display: addon_profile" }
```

I am able to work around this by setting display equal to DISPLAY like so:

``` yaml
- firefox_addon:
    url: https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/
    state: present
  environment:
    display: '{{ ansible_env.DISPLAY }}' 
```

Thanks for this role!
