### ISSUE TITLE
Doesn't work through ssh without X11 forwarding

### ISSUE THREAD

**Issue by petRUShka** [alzadude/ansible-firefox-addon#4]
I connected to Ubuntu machine (without X11 forwarding) and run ansible playbook and playbook was failed:

`fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "{ \"failed\": true, \"msg\": \"couldn't determine profile path\", \"stdout\": \"Error: GDK_BACKEND does not match available displays\" }\n", "module_stdout": "", "msg": "MODULE FAILURE"}
`

Is it possible to get rid of X11 dependency somehow?

**Comment by knarewski** [comment]
This error occurs when script is trying to determine the path to the firefox profile, which is a bit tricky (see: https://askubuntu.com/questions/239543/get-the-default-firefox-profile-directory-from-bash ).

This function will never be called though if you specify the profile manually in the ansible setup, e.g.:
```yml
      - firefox_addon:
        profile: /home/user/.mozilla/firefox/0ke6dn44.default-release
        (...)
```
