### ISSUE TITLE
Alternative Root?

### ISSUE THREAD

**Issue by benyanke** [alzadude/ansible-firefox-addon#6]
When firefox is installed using snap, it's found in `~/snap/firefox/common/.mozilla/firefox`. Would it be possible to provide an option to specify config dir, and perhaps even a snap option to automate this path?

**Comment by knarewski** [comment]
You should be able to do that using `profile` key in the setup, e.g.
```yml
      - firefox_addon:
        profile: /home/user/firefox/common/.mozilla/firefox/0ke6dn44.default-release
        (...)
```
