### ISSUE TITLE
Error when installing addon for firefox on raspbian

### ISSUE THREAD

**Issue by xeloader** [alzadude/ansible-firefox-addon#7]
Code:
```yml
- name: Install auto fullscreen addon
  firefox_addon:
    url: https://addons.mozilla.org/sv-SE/firefox/addon/autofullscreen/
    profile: /home/pi/.mozilla/firefox/sun-screen-profile
    state: present

- name: Install black theme addon
  firefox_addon:
    url: https://addons.mozilla.org/sv-SE/firefox/addon/biack/
    profile: /home/pi/.mozilla/firefox/sun-screen-profile
    state: present
```

Result:
```sh
fatal: [sl-screen-1000000038a16916.local]: FAILED! => {"changed": false, "module_stderr": "Shared connection to sl-screen-1000000038a16916.local closed.\r\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 0}
```

Expected result:
Addon installed

Any ideas why this is? I've installed all of the dependencies.
